---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/hotels
  label: Hotels
  create: all
  match: "**/*"
upload_dir: hugo-site-example-c
public_path: https://res.cloudinary.com/itermotus/image/upload
front_matter_path: "/hugo-cms/hugo-site-example-c"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47.1
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry
version: 0.71.1
